homepage_settings:
  countdown:
    show: true
    timezone: Europe/Berlin
    deadline: 2024-10-14 09:00
  modal:
    show: false
    delay: 9000
  testimonials:
    show: true
    title: "What others say"
  gallery:
    show: true
    title: "Code BEAM Europe 2024"
