homepage_settings:
  countdown:
    show: false
    timezone: Europe/Amsterdam
    deadline: 2026-10-21 08:30
  modal:
    show: false
    delay: 4000
  testimonials:
    show: true
    title: "What others say"
  gallery:
    show: true
    title: "Code BEAM Europe 2026"
  tickets: false
