---
trainers:
  - _participants/erik-stenman.md
  - _participants/robert-virding.md
  - _participants/giacomo-cavalieri.md
  - _participants/hayleigh-thompson.md
  - _participants/gus-workman.md
  - _participants/barnabas-jovanovics.md
  - _participants/francesco-cesarini-new.md
  - _participants/piotr-szmielew.md
