---
trainers:
  - _participants/erik-stenman.md
  - _participants/robert-virding.md
  - _participants/josh-price.md
  - _participants/giacomo-cavalieri.md
  - _participants/gus-workman.md
  - _participants/alvise-susmel.md
  - _participants/piotr-szmielew.md
