---
trainers:
  - _participants/erik-stenman.md
  - _participants/robert-virding.md
  - _participants/giacomo-cavalieri.md
  - _participants/gus-workman.md
  - _participants/barnabas-jovanovics.md
  - _participants/Francesco-cesarini.md
  - _participants/piotr-szmielew.md
