---
trainers:
- _participants/natalia-chechina.md
- _participants/francesco-cesarini-new.md
- _participants/dominik-artur-wolek.md
- _participants/robert-virding.md
- _participants/lukasz-kita.md
- _participants/dominic-letz.md
- _participants/paulo-valente.md
- _participants/lukasz-pauszek.md